### ISSUE TITLE
halp a boi pls!

### ISSUE THREAD

**Issue by igor-dot-gz** [TheDarkHorseUprising/Powersistance#1]
@TheDarkHorseUprising  
i donkt understand???  
how can man be hot if he cant make do some oscp shit???  
btw how does da ting go skrrrraaaa???

**Comment by TheDarkHorseUprising** [comment]
That's a very good question, the answer to Q1) is man's not hot and Q2) like this "skrrraaaaaa!" I hope this halps a boi! 😄
